name: 'Deploy Mautic to DigitalOcean'
description: 'Deploy Mautic 6 with Docker Compose to a DigitalOcean VPS with automated SSL and monitoring'
author: 'escopecz'

branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  # DigitalOcean Configuration
  digitalocean-token:
    description: 'DigitalOcean API access token'
    required: true
  ssh-private-key:
    description: 'SSH private key for VPS access'
    required: true
  
  # Mautic Configuration
  email:
    description: 'Admin email address for Mautic and SSL certificates'
    required: true
  mautic-password:
    description: 'Admin password for Mautic'
    required: true
  mautic-version:
    description: 'Mautic Docker image version'
    required: false
    default: '6.0.5-apache'
  mautic-port:
    description: 'Port for Mautic instance'
    required: false
    default: '8001'
  
  # Optional Configuration
  domain:
    description: 'Domain name for your Mautic instance (optional, will use IP if not provided)'
    required: false
  vps-name:
    description: 'Name for the DigitalOcean droplet'
    required: false
    default: 'mautic-vps'
  vps-size:
    description: 'DigitalOcean droplet size'
    required: false
    default: 's-1vcpu-1gb'
    type: choice
    options:
      - 's-1vcpu-1gb'
      - 's-1vcpu-2gb'
      - 's-2vcpu-2gb'
      - 's-2vcpu-4gb'
      - 's-4vcpu-8gb'
      - 's-8vcpu-16gb'
      - 'c-2'
      - 'c-4'
      - 'c-8'
  vps-region:
    description: 'DigitalOcean region'
    required: false
    default: 'nyc1'
    type: choice
    options:
      - 'nyc1'
      - 'nyc3'
      - 'ams3'
      - 'fra1'
      - 'lon1'
      - 'sgp1'
      - 'tor1'
      - 'sfo3'
      - 'blr1'
      - 'syd1'
  
  # Mautic Packages
  themes:
    description: |
      List of Mautic theme packages from Packagist (one per line):
      vendor/theme-name:^1.0
      another-vendor/custom-theme:dev-main
    required: false
    type: string
  plugins:
    description: |
      List of Mautic plugin packages from Packagist (one per line):
      vendor/plugin-name:^2.0
      another-vendor/custom-plugin:^1.5
    required: false
    type: string
  
  # Database Configuration
  mysql-database:
    description: 'MySQL database name'
    required: false
    default: 'mautic_db'
  mysql-user:
    description: 'MySQL user name'
    required: false
    default: 'mautic_db_user'
  mysql-password:
    description: 'MySQL password'
    required: false
    default: 'mautic_db_pwd'
  mysql-root-password:
    description: 'MySQL root password'
    required: false
    default: 'changeme'

outputs:
  vps-ip:
    description: 'IP address of the created VPS'
    value: ${{ steps.deploy.outputs.vps-ip }}
  mautic-url:
    description: 'URL to access your Mautic instance'
    value: ${{ steps.deploy.outputs.mautic-url }}
  deployment-log:
    description: 'Path to the deployment log artifact'
    value: ${{ steps.deploy.outputs.deployment-log }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        echo "🔍 Validating required inputs..."
        
        if [ -z "${{ inputs.digitalocean-token }}" ]; then
          echo "❌ Error: digitalocean-token is required"
          exit 1
        fi
        
        if [ -z "${{ inputs.ssh-private-key }}" ]; then
          echo "❌ Error: ssh-private-key is required"
          exit 1
        fi
        
        if [ -z "${{ inputs.email }}" ]; then
          echo "❌ Error: email is required"
          exit 1
        fi
        
        if [ -z "${{ inputs.mautic-password }}" ]; then
          echo "❌ Error: mautic-password is required"
          exit 1
        fi
        
        # Validate email format
        if ! echo "${{ inputs.email }}" | grep -E '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' > /dev/null; then
          echo "❌ Error: Invalid email format"
          exit 1
        fi
        
        echo "✅ All required inputs validated"

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.digitalocean-token }}

    - name: Create and configure VPS
      id: deploy
      shell: bash
      run: |
        # Run the main deployment script
        ${{ github.action_path }}/scripts/deploy.sh
        
        # Fail-fast validation: Check if deployment outputs were created
        echo ""
        echo "🔍 Validating deployment..."
        
        # Extract VPS IP from deployment outputs immediately
        VPS_IP=$(grep "vps-ip=" "$GITHUB_OUTPUT" | cut -d'=' -f2-)
        
        # Fail fast if no VPS IP found
        if [ -z "$VPS_IP" ] && [ -z "$INPUT_DOMAIN" ]; then
            echo "❌ FATAL: VPS IP not found in deployment outputs"
            echo "🔍 Deployment appears to have failed - no VPS was created"
            echo "📋 GitHub outputs content:"
            cat "$GITHUB_OUTPUT" 2>/dev/null || echo "No GitHub outputs file found"
            exit 1
        fi
        
        # Set the URL based on domain or IP
        if [ -n "$INPUT_DOMAIN" ]; then
            MAUTIC_URL="https://${INPUT_DOMAIN}"
            echo "VPS IP: ${VPS_IP}"
            echo "Mautic URL: ${MAUTIC_URL} (using domain)"
        else
            MAUTIC_PORT=${INPUT_MAUTIC_PORT:-8001}
            MAUTIC_URL="http://${VPS_IP}:${MAUTIC_PORT}"
            echo "VPS IP: ${VPS_IP}"
            echo "Mautic URL: ${MAUTIC_URL}"
        fi
        
        # Fail fast if URL construction failed
        if [ -z "$MAUTIC_URL" ]; then
            echo "❌ FATAL: Could not construct Mautic URL"
            exit 1
        fi
        
        echo "⏳ Waiting for Mautic to be ready..."
        
        # Test HTTP response with retries - check multiple endpoints
        MAX_ATTEMPTS=3
        ATTEMPT=1
        
        while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            echo "Attempt $ATTEMPT: Testing Mautic endpoints..."
            
            # Test multiple endpoints to diagnose the issue
            BASE_URL="${MAUTIC_URL}"
            LOGIN_URL="${MAUTIC_URL}/s/login"
            
            echo "🔍 Testing base URL: $BASE_URL"
            BASE_HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 10 --max-time 30 "$BASE_URL" 2>/dev/null || echo "000")
            echo "  - Base URL HTTP response: $BASE_HTTP_CODE"
            
            echo "🔍 Testing login URL: $LOGIN_URL"
            LOGIN_HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 10 --max-time 30 "$LOGIN_URL" 2>/dev/null || echo "000")
            echo "  - Login URL HTTP response: $LOGIN_HTTP_CODE"
            
            # Check if either endpoint returns 200 or 302 (redirect is OK)
            if [ "$BASE_HTTP_CODE" = "200" ] || [ "$LOGIN_HTTP_CODE" = "200" ] || [ "$BASE_HTTP_CODE" = "302" ] || [ "$LOGIN_HTTP_CODE" = "302" ]; then
                WORKING_URL="$BASE_URL"
                WORKING_CODE="$BASE_HTTP_CODE"
                if [ "$LOGIN_HTTP_CODE" = "200" ] || [ "$LOGIN_HTTP_CODE" = "302" ]; then
                    WORKING_URL="$LOGIN_URL"
                    WORKING_CODE="$LOGIN_HTTP_CODE"
                fi
                
                echo "✅ Mautic is responding correctly (HTTP $WORKING_CODE on $WORKING_URL)"
                
                # For 302 redirects, this is normal for fresh Mautic installations
                if [ "$WORKING_CODE" = "302" ]; then
                    echo "📋 HTTP 302 detected - Mautic is redirecting (normal for fresh installation/setup)"
                    echo "🎉 Deployment validation successful!"
                    break
                fi
                
                # Additional check: verify the response contains Mautic-specific content
                RESPONSE=$(curl -s --connect-timeout 10 --max-time 30 "$WORKING_URL" 2>/dev/null || echo "")
                if echo "$RESPONSE" | grep -i "mautic" > /dev/null; then
                    echo "✅ Confirmed Mautic application is running correctly"
                    echo "🎉 Deployment validation successful!"
                    break
                else
                    echo "⚠️ Page responded but doesn't contain Mautic content, checking if it's a redirect..."
                    # Check for redirects or alternative indicators
                    if echo "$RESPONSE" | grep -i -E "(login|signin|password)" > /dev/null; then
                        echo "✅ Detected login-related content, Mautic is likely working"
                        echo "🎉 Deployment validation successful!"
                        break
                    fi
                fi
            else
                echo "⚠️ Neither endpoint returned HTTP 200"
                echo "  - Base URL ($BASE_URL): $BASE_HTTP_CODE"
                echo "  - Login URL ($LOGIN_URL): $LOGIN_HTTP_CODE"
                
                # Add immediate debugging on first failure
                if [ $ATTEMPT -eq 1 ]; then
                    echo "🐳 Immediate Docker debugging (first failure):"
                    echo "📋 Container status:"
                    ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ~/.ssh/id_rsa root@${VPS_IP} "cd /var/www && docker compose ps" || echo "Could not get container status"
                    
                    echo "📋 Mautic web container logs (last 20 lines):"
                    ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o ServerAliveInterval=5 -o ServerAliveCountMax=2 -i ~/.ssh/id_rsa root@${VPS_IP} "cd /var/www && timeout 30 docker compose logs --tail=20 mautic_web" || echo "Could not get Mautic logs (connection timeout)"
                    
                    echo "📋 Checking if Mautic is installed in container:"
                    ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o ServerAliveInterval=5 -o ServerAliveCountMax=2 -i ~/.ssh/id_rsa root@${VPS_IP} "cd /var/www && timeout 15 docker compose exec -T mautic_web ls -la /var/www/html/" || echo "Could not list Mautic files (connection timeout)"
                    
                    echo "📋 Checking Apache error logs:"
                    ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o ServerAliveInterval=5 -o ServerAliveCountMax=2 -i ~/.ssh/id_rsa root@${VPS_IP} "cd /var/www && timeout 15 docker compose exec -T mautic_web tail -10 /var/log/apache2/error.log" || echo "Could not get Apache error logs (connection timeout)"
                fi
            fi
            
            if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
                echo "⏳ Waiting 30 seconds before retry..."
                sleep 30
            else
                echo "❌ Mautic failed to respond after $MAX_ATTEMPTS attempts"
                echo "🔍 Final troubleshooting information:"
                echo "  - VPS IP: ${VPS_IP}"
                echo "  - Base URL: ${BASE_URL}"
                echo "  - Login URL: ${LOGIN_URL}"
                echo "  - Base URL response: ${BASE_HTTP_CODE}"
                echo "  - Login URL response: ${LOGIN_HTTP_CODE}"
                
                # Get container status for debugging
                echo "🐳 Container status debugging:"
                ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ~/.ssh/id_rsa root@${VPS_IP} "cd /var/www && docker compose ps" || echo "Could not get container status"
                
                # Check if Mautic is still initializing
                echo "📋 Checking Mautic logs for initialization status:"
                ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ~/.ssh/id_rsa root@${VPS_IP} "cd /var/www && docker compose logs --tail=20 mautic_web" || echo "Could not get Mautic logs"
                
                exit 1
            fi
            
            ATTEMPT=$((ATTEMPT + 1))
        done
      env:
        INPUT_DIGITALOCEAN_TOKEN: ${{ inputs.digitalocean-token }}
        INPUT_SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}
        INPUT_EMAIL: ${{ inputs.email }}
        INPUT_MAUTIC_PASSWORD: ${{ inputs.mautic-password }}
        INPUT_MAUTIC_VERSION: ${{ inputs.mautic-version }}
        INPUT_MAUTIC_PORT: ${{ inputs.mautic-port }}
        INPUT_DOMAIN: ${{ inputs.domain }}
        INPUT_VPS_NAME: ${{ inputs.vps-name }}
        INPUT_VPS_SIZE: ${{ inputs.vps-size }}
        INPUT_VPS_REGION: ${{ inputs.vps-region }}
        INPUT_THEMES: ${{ inputs.themes }}
        INPUT_PLUGINS: ${{ inputs.plugins }}
        INPUT_MYSQL_DATABASE: ${{ inputs.mysql-database }}
        INPUT_MYSQL_USER: ${{ inputs.mysql-user }}
        INPUT_MYSQL_PASSWORD: ${{ inputs.mysql-password }}
        INPUT_MYSQL_ROOT_PASSWORD: ${{ inputs.mysql-root-password }}
        ACTION_PATH: ${{ github.action_path }}

    - name: Upload deployment log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mautic-deployment-log
        path: ./setup-dc.log

    - name: Cleanup
      shell: bash
      if: always()
      run: |
        echo "🧹 Cleaning up SSH keys and temporary files..."
        rm -f ~/.ssh/id_rsa
        rm -f ~/.ssh/id_rsa.pub
        echo "✅ Cleanup completed"