services:
  db:
    image: mysql:8.0
    container_name: mautic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mautic

  mautic:
    image: mautic/mautic:${MAUTIC_VERSION:-6.0.5-apache}
    container_name: mautic_app
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:mysql
    ports:
      - "${PORT:-8001}:80"
    env_file:
      - .mautic_env
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_web
    volumes:
      - mautic_data:/var/www/html
      - ./logs:/var/www/html/var/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost || exit 1"]
      start_period: 90s
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mautic

  # Mautic worker for background processing (disabled by default during initial deployment)
  mautic_worker:
    image: mautic/mautic:${MAUTIC_VERSION:-6.0.5-apache}
    container_name: mautic_worker
    depends_on:
      mautic:
        condition: service_healthy
    links:
      - db:mysql
    env_file:
      - .mautic_env
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
    volumes:
      - mautic_data:/var/www/html
      - ./logs:/var/www/html/var/logs
    command: php /var/www/html/bin/console messenger:consume email async priority normal --limit=10 --memory-limit=512M
    restart: unless-stopped
    profiles:
      - worker  # This allows us to start worker separately after installation
    networks:
      - mautic

volumes:
  mautic_data:
  mysql_data:

networks:
  mautic:
    driver: bridge